### ISSUE TITLE
Standardize morse input keyboard shortcuts

### ISSUE THREAD

**Issue by beckbria** [beckbria/puzztool#104]
GOOD:
. - and Bksp work as they intuitively should.
J and K as shortcuts for dot and dash are fine.

NEEDS WORK:
We should support space for moving to the next character now that we support streams of multiple words, since that's how many users are used to typing in morse code.
We should consider mentioning the keyboard shortcuts on the page somehow.

OPEN QUESTIONS:
1. The convenience shortcuts of J and K for dot and dash are fine.  Should we use L and ; for Bksp and/or Next, or leave those as is with Bksp and space?
2. Do we want to leave Enter in place (in addition to space) for delimiter?  The primary reason would be backcompat for users who have been using the site with Enter currently.

**Comment by beckbria** [comment]
For completeness: Should we have a keyboard shortcut for clear?  I think not, as that's a dangerous one to hit accidentally (unless we implement undo, which is a separate feature request)

**Comment by sjenks** [comment]
I don't think we need clear, beyond maybe ctrl-a ; delete

I like space for a delimiter, ambivalent on enter
